forms:
  corpscanada-incorp:
    path: /corpscanada/registration
    type: issue-credential
    schema_name: registration.corpscanada.ca
    page_title: Corporatations Canada Registry
    title: Registration
    template: corpscanada.index.html
    description: >
      Corporatations Canada Registry administers and supports the legal framework
      used for operating a business, not-for-profit society, cooperative association
      or financial institution in Canada. Organizations need to register, file documents
      and update records, which are kept as a matter of public record.
    explanation: Use the form below to register a BC corporation.

    js_includes:
      - src: js/corpscanada.js

    fields:
      - name: entity_name
        label: Legal Name
        type: text
        required: true

      - name: address
        label: Mailing Address
        type: address
        required: true

    mapping:
      attributes:
        - name: registration_id
          from: helper
          source: uuid

        - name: registration_id
          from: previous
          source: registration_id

        - name: entity_type
          from: literal
          source: CO

        - name: effective_date
          from: helper
          source: now

  corpscanada-dba:
    path: /corpscanada/dba
    type: issue-credential
    schema_name: relationship.corpscanada.ca
    page_title: Corporatations Canada Registry
    title: Doing Business As
    template: corpscanada.index.html
    description: >
      Corporatations Canada Registry administers and supports the legal framework
      used for operating a business, not-for-profit society, cooperative association
      or financial institution in Canada. Organizations need to register, file documents
      and update records, which are kept as a matter of public record.
    explanation: Use the form below to add a Doing Business As name for your business.

    proof_request:
      name: registration
      params:
        source_id: registration_id

    js_includes:
      - src: js/corpscanada.js

    hidden:
      - registration_id

    fields:
      - name: doing_business_as_name
        label: Doing Business As Name
        type: text
        required: true

      - name: address
        label: Mailing Address
        type: address
        required: true

    mapping:
      attributes:
        - name: effective_date
          from: helper
          source: now

